/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and kept here so TypeScript-aware editors
// understand the app structure before dependencies are installed.
